### ISSUE TITLE
Great Work!

### ISSUE THREAD

**Issue by shamork** [TalAloni/StandardSocketsHttpHandler#1]
Great Work!
A good way to fix the  `HttpClient` dns issues

**Comment by shamork** [comment]
BTW, is the 3.1 version (branch 3.1) available? I can't find it in the nuget.org

**Comment by TalAloni** [comment]
Thanks.
I didn't publish 3.1 as NuGet.

**Comment by shamork** [comment]
so ,you think 3.1 version is an available version, just nuget package is missing?
Can I upload the 3.1 version nuget package and leave the package description/github link unchanged?

**Comment by TalAloni** [comment]
I didn't upload the 3.1 version in order to promote the 2.2 version.
3.1 does not bring a lot to the table and is in fact quite confusing because it does not support HTTPS 2.0 (due to missing ALPN support in .NET Standard 2.0)
You are welcome to do as you please with 3.1.
