### ISSUE TITLE
The connection taken from pool which was shut down by the server leads to IOException

### ISSUE THREAD

**Issue by onyxmaster** [TalAloni/StandardSocketsHttpHandler#13]
Hi.
First, I would like to thank you for creating and maintaining this library. The default .NET Framework `HttpClient` implementation based on `HttpWebRequest` is really lacking in terms of stability (especially timeout/cancellation handling), and your library is a great fix for that.

Unfortunately, since we started using it, we encountered the following issue. With some servers which shut down the pooled connections from their own side, the request that follows fails with HttpRequestException wrapping an IOException:
```
System.Net.Http.HttpRequestException: An error occurred while sending the request.
async Task<HttpResponseMessage> System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken) in StandardSocketsHttpHandler/StandardSocketsHttpHandler/Net/Http/SocketsHttpHandler/HttpConnection.cs:line 724
async Task<HttpResponseMessage> System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, bool doRequestAuth, CancellationToken cancellationToken) in StandardSocketsHttpHandler/StandardSocketsHttpHandler/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 316
async Task<HttpResponseMessage> System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, bool doRequestAuth, CancellationToken cancellationToken) in StandardSocketsHttpHandler/StandardSocketsHttpHandler/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 296
...
---> System.IO.IOException: The server returned an invalid or unrecognized response.
async Task<HttpResponseMessage> System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken) in StandardSocketsHttpHandler/StandardSocketsHttpHandler/Net/Http/SocketsHttpHandler/HttpConnection.cs:line 516
```

I believe that this happens due to the [`ConsumeReadAheadTask`](https://github.com/TalAloni/StandardSocketsHttpHandler/blob/2.2/StandardSocketsHttpHandler/Net/Http/SocketsHttpHandler/HttpConnection.cs#L508) reading zero bytes. In the original SocketsHttpHandler this [was addressed](https://github.com/dotnet/runtime/commit/288bfa00fe28b4b25637c362683dd8c6b6573351#diff-595f700a4c83b735d856fe14b5ebe8c7f7c18ae6e586adc8b398a997a0678274). While I understand that you're probably not going to integrate all the "new" changes to SocketsHttpHandler, this one routinely breaks conversations with remote servers and probably is a good candidate for a backport.

I guess we can work around the issue by making the connection pool lifetime smaller for this specific service, but I don't think that will protect us from the problem in all cases.

Thanks for taking a look.

**Comment by TalAloni** [comment]
Hi,
Thanks for the detailed analysis,
This sounds like a very useful change, but I honestly don't have time to dive into it,
A pull request could be very helpful here.

Tal

**Comment by onyxmaster** [comment]
I hope I'll be able to take a look at this next week then.

**Comment by TalAloni** [comment]
Thank you for this pull request.
I've taken a look and it's not clear to me whether this is an optimization or a bugfix, if this is indeed a bugfix, how can I reproduce this bug? what should my server and client do in order for me to experience this bug?

**Comment by onyxmaster** [comment]
This is a bugfix. In order to reproduce the bug, the client should pool connections to server, which shuts them down within the interval that is smaller than pooled connection lifetime. Without this fix, when client attempts to do an initial read of reused connection which has already been closed from the server side, it gets zero bytes, which is considered a fatal error. The fix itself is just a minimal backport of changes in dotnet/runtime that allows internal retry to kick in if the read is, in fact, initial (the body was not already sent).

**Comment by TalAloni** [comment]
I see, so lowering PooledConnectionIdleTimeout (so it would be lower than the server's) would work around the issue, right? (I'm asking to make sure I understand the issue)

**Comment by onyxmaster** [comment]
Yes, it worked for us in our internal testing (that's why I fixed it much later than promised, since I was able to work around with the timeout). Now it works in our production code with the recommended fix with zero failures (it invokes about 30-40 requests per second to different external HTTP APIs).

**Comment by onyxmaster** [comment]
It appears that the SocketsHttpHandler in the `release/6.0` branch of .NET Runtime, works in the same way, so I think "fixing" it here won't do much good. I should either bring it up to .NET developers or get back to setting pool timeouts to expected values.
Thanks for bearing with me =)

**Comment by TalAloni** [comment]
Thank you for the update
