### ISSUE TITLE
Consider building the NuGet package with debug symbols

### ISSUE THREAD

**Issue by onyxmaster** [TalAloni/StandardSocketsHttpHandler#14]
Hi.

When searching for the root cause for #13, I was blocked by the NuGet release missing the debug symbols. I would like to suggest adding the `<DebugType>embedded</DebugType>` to the project file for all configurations. This is easier than doing the full SourceLink stuff, does not add any extra files to the deployment and makes adds only about 40 KB to the built library size, but makes determining the source of exceptions much easier.
For example, compare the stack trace from #13 (where I included the debug symbols) to the following (the one which is produced by using the NuGet build):
```
System.Net.Http.HttpRequestException: An error occurred while sending the request.
async Task<HttpResponseMessage> System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
async Task<HttpResponseMessage> System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, bool doRequestAuth, CancellationToken cancellationToken)
async Task<HttpResponseMessage> System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, bool doRequestAuth, CancellationToken cancellationToken)
 ---> System.IO.IOException: The server returned an invalid or unrecognized response.
async Task<HttpResponseMessage> System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
```
It's much easier to determine where "System.IO.IOException: The server returned an invalid or unrecognized response" is thrown with line numbers, since there are several places in the project where the same exception with the same message is thrown.

**Comment by TalAloni** [comment]
v2.2.0.5 now includes debug symbols
