### ISSUE TITLE
Getting System.NullReferenceException from HasHeaders

### ISSUE THREAD

**Issue by nishantkagrawal** [TalAloni/StandardSocketsHttpHandler#2]
I am getting the following error while using the package in .NET Framework

System.Net.Http.HttpRequestMessageExtensions.HasHeaders(System.Net.Http.HttpRequestMessage)
    System.Net.Http.StandardSocketsHttpHandler.ValidateAndNormalizeRequest(System.Net.Http.HttpRequestMessage)
    System.Net.Http.StandardSocketsHttpHandler.SendAsync(System.Net.Http.HttpRequestMessage, System.Threading.CancellationToken)
    System.Net.Http.DelegatingHandler.SendAsync(System.Net.Http.HttpRequestMessage, System.Threading.CancellationToken)

I am using NET Framework 4.6.1
I have installed System.Net.Http 4.3.4 in my project. 

HttpRequestMessage has a _headers property instead of the expected headers property

#region Assembly System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
// C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Net.Http.dll
#endregion
![image](https://user-images.githubusercontent.com/8187427/114852450-6a90df80-9e00-11eb-8c5f-fd9e8289ae81.png)

**Comment by TalAloni** [comment]
.NET Framework 4.6.1 is not supported. only 4.7.2.
This looks like an easy fix - but I'm not sure if that's the only issue for Framework 4.6.1 and not interested in going down this rabbit hole myself.

**Comment by nishantkagrawal** [comment]
Is it possible for you to expose a property that we can override to avoid this? We have a few hundred microservices for which we would like to use this. It would be a big task for all of them to move to 4.7.2.

**Comment by TalAloni** [comment]
Are you certain that this is the only issue preventing StandardSocketsHttpHandler from working under .NET Framework 4.6.1?

**Comment by Manjula-S** [comment]
Is there any solution for this issue?

**Comment by TalAloni** [comment]
There are two solutions:
1. Update to 4.7.2
2. Create a fork of this project and make the necessary changes for it to work with 4.6.1

**Comment by TalAloni** [comment]
I've added a fallback to avoid this exception in .NET Framework 4.6.1, available in v2.2.0.3
