### ISSUE TITLE
Make it strongly named

### ISSUE THREAD

**Issue by Mek7** [TalAloni/StandardSocketsHttpHandler#22]
Hello,
we couldn't use your nuget package in our solution that is using strong names everywhere, because StandardSocketsHttpHandler doesn't have a strong name.
`Could not load file or assembly 'StandardSocketsHttpHandler, Version=2.2.0.5, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)`
Can you please make it strongly named?

**Comment by TalAloni** [comment]
It's not something I have an interest in, for two reasons:
1. Strong naming is only applicable for client-side applications.
2. StandardSocketsHttpHandler is a library for a niche user-base that has not yet migrated to latest versions of .NET

The combination of the above is a very small niche that I have no interest to cater for.
