### ISSUE TITLE
Make StandardSocketsHttpHandler not sealed?

### ISSUE THREAD

**Issue by hugoqribeiro** [TalAloni/StandardSocketsHttpHandler#4]
Hi.

Any chance to make the handler not sealed?

I'm trying to build a custom HttpClientFactory-like type to manage the lifetime of HttpClient and the underlying handler. This involves overriding Dispose() which cannot be done as StandardSocketsHttpHandler is now...

**Comment by TalAloni** [comment]
Hi,
Microsoft decided for their own reasons that this class will be sealed, and I'm not really keen on making additional changes to the Microsoft implementation beyond those that were added to .NET 5.
Why not creating your own wrapper that implements HttpMessageHandler and use that? (then you can use any HttpMessageHandler)
