### ISSUE TITLE
Status of 3.1?

### ISSUE THREAD

**Issue by thefringeninja** [TalAloni/StandardSocketsHttpHandler#8]
I came across your library and it's just what we're looking for, specifically unencrypted http/2 support in our unit tests. I see it on your 3.1 branch but it's not available on nuget.

**Comment by TalAloni** [comment]
Given that the 3.1 branch is only useful for unencrypted http/2, I thought most people would not find it useful and I did not publish a NuGet for it to avoid stealing focus from the v2.2 branch.
I guess I could publish a NuGet and hide it - seems like very few people would find it useful for production usages.
IIRC Anybody using .NET Core 3 or later could also use unencrypted http/2 natively. (there is a way to enable it IIRC).

**Comment by thefringeninja** [comment]
We have to support net48. A hidden package would work for me.

**Comment by TalAloni** [comment]
Here you go:
https://www.nuget.org/packages/StandardSocketsHttpHandler/3.1.0.1

I've ran the test suite and currently I'm not familiar with any issue, but please consider it as a beta.
